### ISSUE TITLE
How to convert webp to jpg with nodejs?

### ISSUE THREAD

**Issue by taxaser** [poketo/manga-rock-image-decoder#1]
hi,
I try you project to get webp images of mangarock. 
But I hav no idea to convert webp to jpg/png.
could u give some tips?

**Comment by rosszurowski** [comment]
It depends on what you're trying to accomplish. If you're only looking to download jpg/png versions to a file system, you could try using some bash commands and ImageMagick:

```bash
# first, use curl to download the image
curl https://mri-image-decoder.now.sh?url=https://f01.mrcdn.info/file/mrfiles/i/6/n/l/T3.3BZTN7p5.mri > page.webp
# then use imagemagick to convert the .webp to .jpg/.png
convert page.webp page.jpg
```

To do the conversion entirely in Node, I'd recommend using an image processing library like [sharp](https://github.com/lovell/sharp) to help. This example also uses [got](https://www.npmjs.com/package/got) to fetch the .webp image.

```jsx
const got = require('got');
const sharp = require('sharp');

const url = 'https://mri-image-decoder.now.sh?url=https://f01.mrcdn.info/file/mrfiles/i/6/n/l/T3.3BZTN7p5.mri';

got(url, { encoding: null }).then(response => {
  const buffer = response.body;
  return sharp(buffer).toFile('output.png');
}).then(() => {
  console.log('File converted');
});
```

I'm happy give more help if you share more details about what you were trying to accomplish.

**Comment by taxaser** [comment]
```
poketo.getSeries('https://mangarock.com/manga/mrs-serie-48617').then(async data => {
    const {chapters} = data;
    for (let i = 18; i < chapters.length; i++) {
        const name = i + 1 + '_' + chapters[i].title.replace(/\s+/g, "_");
        const dirPath = dir.mkdir('./imgs/Corpse_Party_Blood_Covered/' + name);
        const pageData = await poketo.getChapter(chapters[i].url);
        const {pages} = pageData;
        for (let i = 0; i < pages.length; i++) {
            const getUrl = await got(decode(pages[i].url),{ encoding: null });
            const responseBody = getUrl.body;
            sharp(responseBody).toFile(dirPath+'/'+(i+1)+'.jpg',(err,info)=>{
                console.log(info);
            });
        }
    }
})
```
thanks a lot. it works.

**Comment by rosszurowski** [comment]
No problem, glad you got it working (:

**Comment by rosszurowski** [comment]
@taxaser For what it's worth, I just released [poketo-cli](https://github.com/poketo/poketo-cli) to make downloading manga series easier. It includes a function to convert .webp images to .jpg automatically. Maybe it'll help with whatever you are building.
