### ISSUE TITLE
what are you using node.js version ?

### ISSUE THREAD

**Issue by hoangvn9x** [poketo/manga-rock-image-decoder#2]
what are you using node.js version ?
thank you <3

**Comment by rosszurowski** [comment]
The service at [https://mri-image-decoder.now.sh](https://mri-image-decoder.now.sh) is running on Node 10, which is specified in [the Dockerfile](https://github.com/poketo/manga-rock-image-decoder/blob/master/Dockerfile#L1). The code may work on earlier versions too, but I haven't tested it.

**Comment by hoangvn9x** [comment]
i use : https://nodejs.org/dist/v10.0.0/node-v10.0.0-x64.msi
version 10.0.0 npm 5.6.0
but when i run "node index.js" then "Error: Cannot find module 'got'"

help me. please

**Comment by rosszurowski** [comment]
If you want to run it locally, you'll need to install the dependencies too. Go to the folder you cloned this repository into and run:

```bash
npm install
```

Then, rather than `node index.js`, use the start script included:

```
npm start
```

**Comment by hoangvn9x** [comment]
I was a newbie. can you help me code ?
convert buffer webp to jpg.
thank you so much <3

**Comment by rosszurowski** [comment]
Keep in mind, this project is built as an HTTP server _and_ a node module. The instructions above would help you run a local server like what runs at [https://mri-image-decoder.now.sh](https://mri-image-decoder.now.sh), but you can also use this project in Node like so:

```bash
npm install manga-rock-image-decoder
```

```jsx
const decoder = require('manga-rock-image-decoder');

decode(/* .mri image buffer */);
```

I'll close this issue for now, but feel free to comment if you have other questions.
